cylinder1:
  #waypoint1
  - x: 0.0
    y: 0.2
    z: 0.4
    roll: 0.0
    pitch: 0.0
    yaw: 1.5707
    gripper_state: 0

  #waypoint2
  - j1: 0.23
    j2: 0.5
    j3: 0.8
    j4: 0.7
    j5: 0.9
    j6: 0.1
    gripper_state: 0

  #waypoint3
  - j1: 0.23
    j2: 0.2
    j3: 0.1
    j4: 0.67
    j5: 0.89
    j6: 0.91
    gripper_state: 0

  #attach obj
  - attach: "1"

  #waypoint5
  - x_cartesian: 0.0
    y_cartesian: 0.0
    z_cartesian: 0.1

  #waypoint6
  - x_cartesian: 0
    y_cartesian: -0.2
    z_cartesian: 0.0

  #waypoint7
  - x: 0.422
    y: -0.045
    z: -0.1
    roll: 0.0
    pitch: -0.1
    yaw: 0.0
    gripper_state: 1

  #detach obj
  - detach: "1"


