cylinder1:
  #waypoint0
  - x: 0.0
    y: 0.2
    z: 0.4
    roll: 0.0
    pitch: 0.0
    yaw: 1.5707
    gripper_state: 0

  #waypoint1
  - j1: -1.549
    j2: 0.67804
    j3: 0.6243
    j4: 0.0214
    j5: 1.837
    j6: 1.577
    gripper_state: 0

  #waypoint2
  - j1: -1.549
    j2: 1.0324
    j3: -0.0728
    j4: 0.02377
    j5: 2.1783
    j6: 1.5846
    gripper_state: 0

  #attach obj3
  - attach: "1"

  #waypoint4
  - x_cartesian: 0.0
    y_cartesian: 0.0
    z_cartesian: 0.1

  #waypoint5
  - x_cartesian: 0.0
    y_cartesian: -0.12
    z_cartesian: 0.0

  #waypoint6
  - x: 0.422
    y: -0.045
    z: -0.1
    roll: 0.0
    pitch: -0.1
    yaw: 0.0
    gripper_state: 1

  #detach obj7
  - detach: "1"



cylinder2:
  #waypoint0
  - x: 0.0
    y: 0.2
    z: 0.4
    roll: 0.0
    pitch: 0.0
    yaw: 1.5707
    gripper_state: 0

   #waypoint1
  - j1: -2.3731
    j2: 0.7455
    j3: 0.5392
    j4: -0.82607
    j5: 1.7641
    j6: 1.3606
    gripper_state: 0

    #waypoint2
  - j1: -2.3938
    j2: 1.1443
    j3: -0.1886
    j4: -0.9234
    j5: 1.9681
    j6: 1.09069
    gripper_state: 0

    #attach obj3
  - attach: "2"

    #waypoint4
  - x_cartesian: 0.0
    y_cartesian: 0.0
    z_cartesian: 0.1


    #waypoint5
  - x_cartesian: 0.0
    y_cartesian: -0.12
    z_cartesian: 0.0


    #waypoint6
  - x: 0.422
    y: -0.17
    z: -0.1
    roll: 0.0
    pitch: -0.1
    yaw: 0.0
    gripper_state: 1

    #detach obj7
  - detach: "2"



cylinder3:
  #waypoint0
  - x: 0.0
    y: 0.2
    z: 0.4
    roll: 0.0
    pitch: 0.0
    yaw: 1.5707
    gripper_state: 0

  #waypoint1
  - x: -0.15
    y: 0.38
    z: 0.5
    roll: 0.0
    pitch: 0.0
    yaw: 1.5707
    gripper_state: 0

  #waypoint2
  - x_cartesian: 0.0
    y_cartesian: 0.0
    z_cartesian: -0.12

  #waypoint3
  - attach: "3"

  #waypoint4
  - x: 0.422
    y: -0.31
    z: -0.1
    roll: 0.0
    pitch: -0.1
    yaw: 0.0
    gripper_state: 1

  
  #waypoint5
  - detach: "3"



cylinder4:
  #waypoint0
  - x: 0.0
    y: 0.2
    z: 0.4
    roll: 0.0
    pitch: 0.0
    yaw: 1.5707
    gripper_state: 0

  #waypoint1
  - j1: 1.5969
    j2: -0.5392
    j3: 0.70181
    j4: 0.17411
    j5: -0.1633
    j6: 1.7426
    gripper_state: 0

  
  #waypoint2
  - j1: 1.6736241145379016
    j2: -0.5054620950872949
    j3: 0.5929016684407874
    j4: 0.959534265484379
    j5: -0.13882949804370312
    j6: -2.4973969371839635
    gripper_state: 0


  #waypoint3
  - attach: "4"

  #waypoint4
  - x: 0.422
    y: -0.123
    z: 0.16459
    roll: 0.0
    pitch: -0.1
    yaw: 0.0
    gripper_state: 1

  #waypoint5
  - detach: "4"



cylinder5:
  #waypoint0
  - x: 0.0
    y: 0.2
    z: 0.4
    roll: 0.0
    pitch: 0.0
    yaw: 1.5707
    gripper_state: 0

  #waypoint1
  - x: 0.15
    y: 0.58
    z: 0.4
    roll: 0.0
    pitch: 0.0
    yaw: 1.5707
    gripper_state: 0

  
  #waypoint2
  - x_cartesian: 0.0
    y_cartesian: 0.0
    z_cartesian: -0.1


  #waypoint3
  - attach: "5"

  #waypoint4
  - x: 0.422
    y: -0.222
    z: 0.16459
    roll: 0.0
    pitch: -0.1
    yaw: 0.0
    gripper_state: 1

  #waypoint5
  - detach: "5"




cylinder6:
  #waypoint0
  - x: 0.0
    y: 0.2
    z: 0.4
    roll: 0.0
    pitch: 0.0
    yaw: 1.5707
    gripper_state: 0

  #waypoint1
  - x: -0.15
    y: 0.58
    z: 0.4
    roll: 0.0
    pitch: 0.0
    yaw: 1.5707
    gripper_state: 0

  
  #waypoint2
  - x_cartesian: 0.0
    y_cartesian: 0.0
    z_cartesian: -0.1


  #waypoint3
  - attach: "6"

  #waypoint4
  - x: 0.420
    y: -0.18
    z: 0.5
    roll: 0.0
    pitch: -0.1
    yaw: 0.0
    gripper_state: 1

  #waypoint5
  - detach: "6"

  #waypoint6
  - x: 0.0
    y: 0.2
    z: 0.4
    roll: 0.0
    pitch: 0.0
    yaw: 1.5707
    gripper_state: 0