cylinder1:
  #waypoint1
  - x: 0.0
    y: 0.2
    z: 0.4
    roll: 0.0
    pitch: 0.0
    yaw: 1.5707
    gripper_state: 0

  #waypoint2
  - j1: -2.26
    j2: 0.6366
    j3: 0.711
    j4: 2.4345
    j5: -1.7388
    j6: -1.7127
    gripper_state: 0

  #waypoint3
  - j1: -2.24
    j2: 0.9656
    j3: 0.04525
    j4: 2.38311
    j5: -1.997
    j6: -1.942
    gripper_state: 0

  #attach obj
  - attach: "1"

  #waypoint5
  - x_cartesian: 0.0
    y_cartesian: 0.0
    z_cartesian: 0.1

  #waypoint6
  - x_cartesian: 0.0
    y_cartesian: -0.2
    z_cartesian: 0.0

  #waypoint7
  - x: 0.422
    y: -0.045
    z: -0.1
    roll: 0.0
    pitch: -0.1
    yaw: 0.0
    gripper_state: 1

  #detach obj
  - detach: "1"


